### ISSUE TITLE
doesn't like media type

### ISSUE THREAD

**Issue by j2l** [benlawraus/yaml2schema#1]
Thank you for this tool!
I'm interested in your approach.
On the Anvil NEWS tutorial data, it stumbles on the media type:
```
Traceback (most recent call last):
  File "yaml2schema-master/src/yaml2schema/main.py", line 89, in <module>
    if not main():
  File "yaml2schema-master/src/yaml2schema/main.py", line 35, in main
    open_api_yaml = convert_anvil_to_openapi_yaml(parsed_yaml)
  File "yaml2schema-master/src/yaml2schema/y2s_to_openapi.py", line 60, in convert_anvil_to_openapi_yaml
    type_col = OPENAPI_TYPES[type_col]
KeyError: 'media'
```
changing it to image, url doesn't work, only string type is allowed?

**Comment by benlawraus** [comment]
Yes… strictyaml is too strict. I’ll see about making it looser….

On Mon, May 9, 2022, at 12:00 AM, Philippe Manzano wrote:
> 
> 
> 
> Thank you for this tool!
> I'm interested in your approach.
> On the Anvil NEWS tutorial data, it stumbles on the media type:
> 
> `Traceback (most recent call last):
>   File "yaml2schema-master/src/yaml2schema/main.py", line 89, in <module>
>     if not main():
>   File "yaml2schema-master/src/yaml2schema/main.py", line 35, in main
>     open_api_yaml = convert_anvil_to_openapi_yaml(parsed_yaml)
>   File "yaml2schema-master/src/yaml2schema/y2s_to_openapi.py", line 60, in convert_anvil_to_openapi_yaml
>     type_col = OPENAPI_TYPES[type_col]
> KeyError: 'media'
`

**Comment by benlawraus** [comment]
HI
I made some changes.
Now when I use https://github.com/benlawraus/pyDALAnvilWorksDev with a clone of the news app
(https://anvil.works/build#clone:RLPRLKUK3VPTTXUH%3dQSLBZG4MRQGVNS7CZZXJKBPQ),
 the setup script runs without errors. I ran it on my MacBook.

I should say that pyDALAnvilWorksDev uses yaml2schema as a submodule...

regards
Ben

On Mon, May 9, 2022, at 12:00 AM, Philippe Manzano wrote:
> 
> 
> 
> Thank you for this tool!
> I'm interested in your approach.
> On the Anvil NEWS tutorial data, it stumbles on the media type:
> 
> `Traceback (most recent call last):
>   File "yaml2schema-master/src/yaml2schema/main.py", line 89, in <module>
>     if not main():
>   File "yaml2schema-master/src/yaml2schema/main.py", line 35, in main
>     open_api_yaml = convert_anvil_to_openapi_yaml(parsed_yaml)
>   File "yaml2schema-master/src/yaml2schema/y2s_to_openapi.py", line 60, in convert_anvil_to_openapi_yaml
>     type_col = OPENAPI_TYPES[type_col]
> KeyError: 'media'
`

**Comment by j2l** [comment]
Yay, super cool!
Thank you!

**Comment by benlawraus** [comment]
Hi, FYI I just tried a simple pytest on this app on my laptop within pyCharm:
```
from tests import pydal_def as mydal

class TestApp:
    def test_home_init(self):
        mydal.define_tables_of_db()
        from client_code.Homepage import Homepage
        form = Homepage()
```
and it passed ok.
